# SPDX-FileCopyrightText: 2025 DB Systel GmbH
#
# SPDX-License-Identifier: Apache-2.0

changelog:
  categories:
    - title: Features and Fixes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - Renovate
    - title: Dependencies
      labels:
        - dependencies
        - Renovate
